import { Workout, ExerciseDefinition } from './fitness';

export const INITIAL_EXERCISE_DEFINITIONS: ExerciseDefinition[] = [
  { id: 'e1', name: 'Incline DB Press', target: 'Upper Chest', tags: ['priority'] },
  { id: 'e2', name: 'DB Shoulder Press', target: 'Shoulders Overall', tags: [] },
  { id: 'e3', name: 'Flat Machine Press', target: 'Mid Chest', tags: [] },
  { id: 'e4', name: 'Cable Lateral Raise', target: 'Side Delts', tags: ['priority'] },
  { id: 'e5', name: 'V-Bar Pushdown', target: 'Triceps', tags: [] },
  { id: 'e6', name: 'Barbell Wrist Curl', target: 'Inner Forearm', tags: ['daily'] },
  { id: 'e7', name: 'Lat Pulldown (Wide)', target: 'Lats Width', tags: [] },
  { id: 'e8', name: 'Seated Cable Row', target: 'Mid-Back', tags: [] },
  { id: 'e9', name: 'Face Pulls', target: 'Rear Delts', tags: ['priority'] },
  { id: 'e10', name: 'Straight-Arm Pulldown', target: 'Lats/V-Taper', tags: [] },
  { id: 'e11', name: 'Hammer Curls', target: 'Forearm/Bicep', tags: ['daily'] },
  { id: 'e12', name: 'Pec Deck Fly', target: 'Inner Chest', tags: [] },
  { id: 'e13', name: 'Cable Crossover', target: 'Chest Stretch', tags: [] },
  { id: 'e14', name: 'Goblet Squat', target: 'Quads/Glutes', tags: [] },
  { id: 'e15', name: 'Romanian Deadlift', target: 'Hamstrings/Back', tags: [] },
  { id: 'e16', name: 'Plate Pinch Holds', target: 'Grip/Forearm', tags: ['daily'] },
  { id: 'e17', name: 'Incline Machine Press', target: 'Upper Chest', tags: ['priority'] },
  { id: 'e18', name: 'Machine Shoulder Press', target: 'Shoulders Mass', tags: [] },
  { id: 'e19', name: 'DB Lateral Raise', target: 'Side Delts', tags: ['priority'] },
  { id: 'e20', name: 'Reverse Pec Deck', target: 'Rear Delts', tags: [] },
  { id: 'e21', name: 'Overhead Cable Ext.', target: 'Tricep Long Head', tags: [] },
  { id: 'e22', name: 'Reverse BB Curl', target: 'Top Forearm', tags: ['daily'] },
  { id: 'e23', name: 'Chest Supported Row', target: 'Mid-Back', tags: [] },
  { id: 'e24', name: 'Lat Pulldown (Close)', target: 'Lower Lats', tags: [] },
  { id: 'e25', name: 'Single-Arm Cable Fly', target: 'Rear Delts', tags: [] },
  { id: 'e26', name: 'EZ-Bar Bicep Curls', target: 'Biceps', tags: [] },
  { id: 'e27', name: 'Wrist Rotations (DB)', target: 'Forearm Rot.', tags: ['daily'] },
  { id: 'e28', name: 'Machine Lat. Raise', target: 'Side Delts', tags: [] },
  { id: 'e29', name: 'Leg Press', target: 'Quads/Glutes', tags: [] },
  { id: 'e30', name: 'Glute Kickback', target: 'Glutes', tags: [] },
  { id: 'e31', name: 'Seated Calf Raise', target: 'Calves', tags: [] },
  { id: 'e32', name: 'Hanging Leg Raises', target: 'Abs/Core', tags: [] },
  { id: 'e33', name: 'Behind-Back Curls', target: 'Inner Forearm', tags: ['daily'] },
  { id: 'e34', name: 'Cable Curl (Rope)', target: 'Biceps/Peak', tags: [] },
  { id: 'e35', name: 'Incline Barbell Press', target: 'Upper Chest', tags: ['priority'] },
  { id: 'e36', name: 'Flat DB Press', target: 'Mid Chest', tags: [] },
  { id: 'e37', name: 'Weighted Pull-Up', target: 'Lats/Back Width', tags: ['priority'] },
  { id: 'e38', name: 'Close-Grip Bench Press', target: 'Triceps', tags: [] },
  { id: 'e39', name: 'Barbell Back Squat', target: 'Quads/Glutes', tags: ['priority'] },
  { id: 'e40', name: 'Lying Leg Curl', target: 'Hamstrings', tags: [] },
  { id: 'e41', name: 'Standing Calf Raise', target: 'Calves', tags: [] },
];

export const INITIAL_WORKOUTS: Workout[] = [
  {id:'push-a',name:'Push Day A',badge:'DAY 1 · PUSH A',type:'push',cycleDay:1,isCore:true,
   exercises:[
    {exerciseDefinitionId:'e1',sets:4,reps:'8–10',note:'45° elbow tuck; focus on the deep stretch.'},
    {exerciseDefinitionId:'e2',sets:3,reps:'8–10',note:'Keep palms slightly inward for joint safety.'},
    {exerciseDefinitionId:'e3',sets:3,reps:'10–12',note:'Keep shoulder blades pinned; don\'t lock out elbows.'},
    {exerciseDefinitionId:'e4',sets:3,reps:'12–15',note:'Pull across the body; constant tension.'},
    {exerciseDefinitionId:'e5',sets:3,reps:'10–12',note:'Heavy power move; keep elbows glued to your ribs.'},
    {exerciseDefinitionId:'e6',sets:3,reps:'15–20',note:'Let bar roll to fingertips for maximum mass.'},
   ],cardio:{name:'Incline Treadmill Walk',detail:'12% incline · 4.5 km/h · No rail holds',duration:"10'"}},

  {id:'pull-a',name:'Pull Day A',badge:'DAY 2 · PULL A',type:'pull',cycleDay:2,isCore:true,
   exercises:[
    {exerciseDefinitionId:'e7',sets:3,reps:'10–12',note:'Pull with your elbows; arch back slightly at bottom.'},
    {exerciseDefinitionId:'e8',sets:3,reps:'10–12',note:'Neutral grip; squeeze shoulder blades hard for 1 sec.'},
    {exerciseDefinitionId:'e9',sets:3,reps:'15–20',note:'Pull rope toward ears; keep elbows high.'},
    {exerciseDefinitionId:'e10',sets:3,reps:'12–15',note:'Finish the V-taper; keep arms straight throughout.'},
    {exerciseDefinitionId:'e11',sets:3,reps:'10–12',note:'Thumbs up; fills the top of the forearm/arm.'},
   ],cardio:{name:'Stationary Bike',detail:'Moderate pace; steady rhythmic breathing',duration:"10'"}},

  {id:'hybrid-a',name:'Hybrid Day A',badge:'DAY 3 · HYBRID A',type:'hybrid',cycleDay:3,isCore:true,
   exercises:[
    {exerciseDefinitionId:'e12',sets:3,reps:'12–15',note:'Massive stretch; don\'t let handles touch.'},
    {exerciseDefinitionId:'e13',sets:3,reps:'12–15',note:'Focus on the hug and the squeeze at the center.'},
    {exerciseDefinitionId:'e14',sets:3,reps:'10–12',note:'Deep reps; hold weight tight to your collarbone.'},
    {exerciseDefinitionId:'e15',sets:3,reps:'12',note:'Push hips back; keep weights close to your shins.'},
    {exerciseDefinitionId:'e16',sets:3,reps:'Max',note:'Squeeze two plates; hold until failure.'},
   ],cardio:{name:'Fast Incline Walk',detail:'15% incline · High metabolic demand',duration:"10'"}},

  {id:'rest-1',name:'Recovery Day',badge:'DAY 4 · REST',type:'rest',cycleDay:4,isCore:true,
   exercises:[],restNotes:['122g Protein · Hit your target','3L Water · Full hydration','CNS & Muscle Repair · No training'],cardio:null},

  {id:'push-b',name:'Push Day B',badge:'DAY 5 · PUSH B',type:'push',cycleDay:5,isCore:true,
   exercises:[
    {exerciseDefinitionId:'e17',sets:4,reps:'10–12',note:'Safe to push to absolute muscle failure.'},
    {exerciseDefinitionId:'e18',sets:3,reps:'10–12',note:'Excellent for heavy, stable loading on the delts.'},
    {exerciseDefinitionId:'e19',sets:3,reps:'15–20',note:'Lean slightly forward; pinky-finger up.'},
    {exerciseDefinitionId:'e20',sets:3,reps:'12–15',note:'Palms facing each other; keep constant tension.'},
    {exerciseDefinitionId:'e21',sets:3,reps:'10–12',note:'Hits the back of the arm for side-profile girth.'},
    {exerciseDefinitionId:'e22',sets:3,reps:'12–15',note:'Overhand grip for the watch-popping muscle.'},
   ],cardio:{name:'Bike Intervals',detail:'30s fast / 30s slow recovery',duration:"10'"}},

  {id:'pull-b',name:'Pull Day B',badge:'DAY 6 · PULL B',type:'pull',cycleDay:6,isCore:true,
   exercises:[
    {exerciseDefinitionId:'e23',sets:3,reps:'8–10',note:'Drive elbows back; eliminate all body momentum.'},
    {exerciseDefinitionId:'e24',sets:3,reps:'10–12',note:'Use V-Bar; pull toward your lower ribs.'},
    {exerciseDefinitionId:'e25',sets:3,reps:'15 ea',note:'Stand upright; pull cable across body.'},
    {exerciseDefinitionId:'e26',sets:3,reps:'10–12',note:'Focus on the peak squeeze at the top.'},
    {exerciseDefinitionId:'e27',sets:3,reps:'12 ea',note:'Hold DB at very end; rotate slowly.'},
   ],cardio:{name:"Farmer's Carry",detail:'Heavy DBs · Tall chest, proud posture',duration:"10'"}},

  {id:'hybrid-b',name:'Hybrid Day B',badge:'DAY 7 · HYBRID B',type:'hybrid',cycleDay:7,isCore:true,
   exercises:[
    {exerciseDefinitionId:'e28',sets:3,reps:'15',note:'Constant isolation shoulder finisher.'},
    {exerciseDefinitionId:'e29',sets:3,reps:'12–15',note:'Feet shoulder-width; push through your heels.'},
    {exerciseDefinitionId:'e30',sets:3,reps:'12 ea',note:'Slow and controlled; squeeze at the top.'},
    {exerciseDefinitionId:'e31',sets:3,reps:'15–20',note:'2-sec pause at bottom stretch; explode up.'},
    {exerciseDefinitionId:'e32',sets:3,reps:'15',note:'Don\'t swing; use core to lift legs.'},
    {exerciseDefinitionId:'e33',sets:3,reps:'15–20',note:'BB behind glutes; short, intense pulses.'},
   ],cardio:{name:'Power Incline Walk',detail:'15% incline · Finish the 8-day cycle strong',duration:"10'"}},

  {id:'rest-2',name:'Recovery Day',badge:'DAY 8 · REST',type:'rest',cycleDay:8,isCore:true,
   exercises:[],restNotes:['Deep sleep 8+ hours · Non-negotiable','Nutrition check · Review macros','Cycle resets tomorrow · Stay ready'],cardio:null},

  {id:'date-night',name:'Date Night',badge:'BONUS · DATE NIGHT',type:'date',cycleDay:null,isCore:false,
   exercises:[
    {exerciseDefinitionId:'e1',sets:4,reps:'10–12',note:'Moderate weight, controlled tempo. Pump focus.'},
    {exerciseDefinitionId:'e12',sets:3,reps:'12–15',note:'Full stretch — the stretch builds the pump.'},
    {exerciseDefinitionId:'e19',sets:4,reps:'15–20',note:'Gives shoulder width that shows in any shirt.'},
    {exerciseDefinitionId:'e18',sets:3,reps:'10–12',note:'Controlled, not heavy. Pump, not fatigue.'},
    {exerciseDefinitionId:'e34',sets:3,reps:'12–15',note:'Supinate hard at the top for the peak.'},
    {exerciseDefinitionId:'e21',sets:3,reps:'12–15',note:'Full stretch overhead — big visual impact.'},
    {exerciseDefinitionId:'e6',sets:3,reps:'15–20',note:'Pumped forearms are the finishing touch.'},
   ],cardio:{name:'Incline Treadmill Walk',detail:'10% incline · Keeps the pump',duration:"10'"}},

  {id:'upper-body',name:'Upper Body',badge:'BONUS · UPPER BODY',type:'upper',cycleDay:null,isCore:false,
   exercises:[
    {exerciseDefinitionId:'e35',sets:4,reps:'6–8',note:'Main strength driver. Push heavy here.'},
    {exerciseDefinitionId:'e36',sets:3,reps:'8–10',note:'Greater range of motion than barbell.'},
    {exerciseDefinitionId:'e37',sets:4,reps:'6–8',note:'Best bang-for-buck back exercise.'},
    {exerciseDefinitionId:'e23',sets:3,reps:'8–10',note:'No momentum. Pure mid-back isolation.'},
    {exerciseDefinitionId:'e4',sets:4,reps:'12–15',note:'Shoulder priority — don\'t rush it.'},
    {exerciseDefinitionId:'e26',sets:3,reps:'10–12',note:'Controlled negative on the way down (2–3 sec).'},
    {exerciseDefinitionId:'e38',sets:3,reps:'8–10',note:'Compounds build tricep mass faster than pushdowns.'},
   ],cardio:{name:'Bike Intervals',detail:'30s hard / 30s easy · Post-upper session',duration:"10'"}},

  {id:'lower-body',name:'Lower Body',badge:'BONUS · LOWER BODY',type:'lower',cycleDay:null,isCore:false,
   exercises:[
    {exerciseDefinitionId:'e39',sets:4,reps:'6–8',note:'King of lower body. Break parallel every rep.'},
    {exerciseDefinitionId:'e29',sets:4,reps:'10–12',note:'After squats, go heavy. Push through heels.'},
    {exerciseDefinitionId:'e15',sets:4,reps:'8–10',note:'Most underrated leg exercise. Feel the stretch.'},
    {exerciseDefinitionId:'e40',sets:3,reps:'10–12',note:'Fully exhaust hamstrings after RDL.'},
    {exerciseDefinitionId:'e30',sets:3,reps:'12 ea',note:'Cable keeps tension throughout.'},
    {exerciseDefinitionId:'e41',sets:4,reps:'15–20',note:'2 sec pause at bottom. Calves respond to stretch.'},
    {exerciseDefinitionId:'e32',sets:3,reps:'15',note:'Use core to initiate, not momentum.'},
   ],cardio:{name:'Power Incline Walk',detail:'15% incline · Quad & glute burn finisher',duration:"10'"}}
];
